### ISSUE TITLE
how do i even launch it? im not seeing an exe anywhere

### ISSUE THREAD

**Issue by MadArtificer13** [dealloc/icarus_editor#10]

**Comment by dealloc** [comment]
hi @MadArtificer13 you can check the [releases](https://github.com/dealloc/icarus_editor/releases) there you should be able to download a ZIP file for your OS (Windows 10/Windows 11 are currently supported) that contains the ZIP.

Make sure you _extract_ the zip file before running the EXE as otherwise it might not work.
